// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesOrderApp.Models;

#nullable disable

namespace SalesOrderApp.Migrations
{
    [DbContext(typeof(SalesOrderContext))]
    [Migration("20250921222120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesOrderApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Systems"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Games"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Controllers"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Protective Gear"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Audio Equipment"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Misc Accessories"
                        });
                });

            modelBuilder.Entity("SalesOrderApp.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Nintendo Switch 2",
                            ProductPrice = 450m,
                            ProductQty = 15
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 2,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Mario Kart World",
                            ProductPrice = 80m,
                            ProductQty = 45
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 3,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Joy-Con 2 Pair",
                            ProductPrice = 100m,
                            ProductQty = 20
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 4,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Nintendo Switch 2 Rough Carrying Case",
                            ProductPrice = 30m,
                            ProductQty = 7
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 5,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "PanaSonic Ergofit Earbuds ",
                            ProductPrice = 12m,
                            ProductQty = 11
                        });
                });

            modelBuilder.Entity("SalesOrderApp.Models.Product", b =>
                {
                    b.HasOne("SalesOrderApp.Models.Category", "Category")
                        .WithOne("Product")
                        .HasForeignKey("SalesOrderApp.Models.Product", "CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SalesOrderApp.Models.Category", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
