using System.ComponentModel.DataAnnotations.Schema;

namespace Project2_FAQs.Models
{
    public class Faq
    {
        public int Id { get; set; }  // Primary key generated by DB
        public string Question { get; set; } = string.Empty;
        public string Answer { get; set; } = string.Empty;

        public string TopicId { get; set; } = string.Empty;
        [ForeignKey("TopicId")]
        public Topic? Topic { get; set; }

        public string CategoryId { get; set; } = string.Empty;
        [ForeignKey("CategoryId")]
        public Category? Category { get; set; }
    }
}