// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2_FAQs.Models;

#nullable disable

namespace Project2_FAQs.Migrations
{
    [DbContext(typeof(FaqContext))]
    [Migration("20250923004924_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project2_FAQs.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "general",
                            Name = "General"
                        },
                        new
                        {
                            Id = "history",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Project2_FAQs.Models.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Bootstrap is a front-end framework for building responsive web sites and applications.",
                            CategoryId = "general",
                            Question = "What is Bootstrap?",
                            TopicId = "bootstrap"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Bootstrap was first released in 2011.",
                            CategoryId = "history",
                            Question = "When was Bootstrap first released?",
                            TopicId = "bootstrap"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "C# is a modern, object-oriented programming language developed by Microsoft.",
                            CategoryId = "general",
                            Question = "What is C#?",
                            TopicId = "csharp"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "C# was first released in 2002.",
                            CategoryId = "history",
                            Question = "When was C# first released?",
                            TopicId = "csharp"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "JavaScript is a high-level, dynamic programming language used primarily for web development.",
                            CategoryId = "general",
                            Question = "What is JavaScript?",
                            TopicId = "javascript"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "JavaScript was first released in 1995.",
                            CategoryId = "history",
                            Question = "When was JavaScript first released?",
                            TopicId = "javascript"
                        });
                });

            modelBuilder.Entity("Project2_FAQs.Models.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = "bootstrap",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = "csharp",
                            Name = "C#"
                        },
                        new
                        {
                            Id = "javascript",
                            Name = "JavaScript"
                        });
                });

            modelBuilder.Entity("Project2_FAQs.Models.Faq", b =>
                {
                    b.HasOne("Project2_FAQs.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project2_FAQs.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
